# Generated by Django 6.0.2 on 2026-06-04 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0013_perfil_rfc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='curp',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='rfc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
